projects:
  - name: "Dataset"
    description: "Informazioni relative ai dataset della Città di Padova"
    short_name: dataset
    documents:
      - mobilita-data
    website: http://www.padovanet.it/
    tags:
      - dataset
      - open data
      - data
